    ini_open("speedshard.ini")
    global.defaut_gamespeed = ini_read_real("globals", "default_gamespeed", 40)
    global.accelerated_gamespeed = ini_read_real("globals", "accelerated_gamespeed", 40)
    global.reputation_modifier = ini_read_real("globals", "reputation_modifier", 1)
    global.water_container_modifier = ini_read_real("globals", "water_container_modifier", 1)
    global.campbed_despawn_days = ini_read_real("globals", "campbed_despawn_days", 1)
    global.hostile_spawnrate_by_level_modifier = ini_read_real("globals", "hostile_spawnrate_by_level_modifier", 31)
    global.neutral_spawnrate_by_level_modifier = ini_read_real("globals", "neutral_spawnrate_by_level_modifier", 31)
    global.tiles_by_turn = ini_read_real("globals", "tiles_by_turn", 1)
    global.xp_by_level_modifier = ini_read_real("globals", "xp_by_level_modifier", 500)
    global.max_level = ini_read_real("globals", "max_level", 30)
    global.interval_level_extra_sp = ini_read_real("globals", "interval_level_extra_sp", 31)
    global.interval_level_extra_ap = ini_read_real("globals", "interval_level_extra_ap", 31)
    global.dungeon_reset_modifier = ini_read_real("globals", "dungeon_reset_modifier", 6)
    global.extra_sp_ap_at_creation = ini_read_real("globals", "extra_sp_ap_at_creation", 0)
    global.quicksave_enable = ini_read_real("globals", "quicksave_enable", 0)
    global.campbed_not_destroyed = ini_read_real("globals", "campbed_not_destroyed", 0)
    global.big_backpack = ini_read_real("globals", "big_backpack", 0)
    global.secret_room_chance = ini_read_real("globals", "secret_room_chance", 5)
    global.contract_money_modifier = ini_read_real("globals", "contract_money_modifier", 1)
    global.number_room_max = ini_read_real("globals", "number_room_max", 15)
    global.number_room_min = ini_read_real("globals", "number_room_min", 5)
    global.number_chest_max = ini_read_real("globals", "number_chest_max", 7)
    global.number_chest_min = ini_read_real("globals", "number_chest_min", 5)
    global.extra_slotbar = ini_read_real("globals", "extra_slotbar", 0)
    global.gold_multiplier = ini_read_real("globals", "gold_multiplier", 1)
    ini_close()
    global.gamespeed = global.defaut_gamespeed